language: python
python:
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
branches:
  only:
  - main
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - sh run_tests.sh
